spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql:true
  datasource:
    url:jdbc:mysql://localhost:3306/school_managment?createDatabaseIfNotExist=true
    username: root
    password: